import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#050505',
        'on-primary-container': '#e0f2fe',
        'outline-variant': '#1f2937',
        'primary-container': '#002b3d',
        'error-container': '#9f0519',
        'inverse-surface': '#faf8ff',
        'primary-fixed-dim': '#0ea5e9',
        outline: '#374151',
        'surface-container': '#080808',
        'surface-tint': '#3bbffa',
        'primary-dim': '#0ea5e9',
        error: '#f87171',
        'on-secondary-fixed': '#94a3b8',
        'on-primary': '#082f49',
        'tertiary-dim': '#818cf8',
        'surface-container-lowest': '#000000',
        'on-secondary-container': '#e2e8f0',
        'on-error-container': '#fecaca',
        'secondary-dim': '#cbd5e1',
        'tertiary-fixed-dim': '#a5b4fc',
        'tertiary-container': '#312e81',
        tertiary: '#818cf8',
        'on-tertiary-fixed-variant': '#3730a3',
        'on-primary-fixed-variant': '#075985',
        'surface-bright': '#111111',
        'secondary-fixed-dim': '#94a3b8',
        'on-secondary': '#1e293b',
        'on-background': '#f8fafc',
        'on-tertiary-fixed': '#e0e7ff',
        'tertiary-fixed': '#c7d2fe',
        'surface-container-highest': '#0c0c0c',
        primary: '#38bdf8',
        'secondary-fixed': '#f1f5f9',
        'surface-container-high': '#0a0a0a',
        'secondary-container': '#1e293b',
        background: '#020202',
        'on-error': '#450a0a',
        'surface-dim': '#020202',
        surface: '#020202',
        'inverse-on-surface': '#94a3b8',
        'on-primary-fixed': '#f0f9ff',
        'on-surface': '#f8fafc',
        'error-dim': '#ef4444',
        'on-secondary-fixed-variant': '#475569',
        'inverse-primary': '#0369a1',
        'on-tertiary-container': '#e0e7ff',
        'on-tertiary': '#1e1b4b',
        'surface-variant': '#0c0c0c',
        'on-surface-variant': '#94a3b8',
        secondary: '#f1f5f9',
        'primary-fixed': '#0ea5e9',
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.5rem',
        xl: '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
